name: Compile Android APK

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  release:
    types:
      - published
      - prereleased
  workflow_dispatch:

jobs:
  build-arm64:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.101

    - name: Install Android workload
      run: |
        sudo apt-get update
        sudo apt-get install -y unzip wget openjdk-17-jdk
        dotnet workload install android

    - name: Restore dependencies
      run: dotnet restore -r android-arm64 --configfile GalaxyBudsClient/nuget.config GalaxyBudsClient.Android/GalaxyBudsClient.Android.csproj

    - name: Build Release APK
      run: dotnet publish GalaxyBudsClient.Android/GalaxyBudsClient.Android.csproj \
        -f net8.0-android \
        -c Release \
        -r android-arm64 \
        -p:EmbedAssembliesIntoApk=true \
        -p:AndroidSupportedAbis=arm64-v8a \
        -p:AndroidPackageFormat=apk \
        -o bin_android

    - name: Generate debug keystore
      run: |
        mkdir -p keystore
        keytool -genkeypair -v -keystore keystore/debug.keystore -storepass android -alias androiddebugkey -keypass android -keyalg RSA -keysize 2048 -validity 10000 -dname "CN=Debug,O=Debug,L=Debug,ST=Debug,C=US"

    - name: Sign APK
      run: |
        jarsigner -verbose -sigalg SHA256withRSA -digestalg SHA-256 \
        -keystore keystore/debug.keystore -storepass android -keypass android \
        bin_android/*.apk androiddebugkey

    - name: Align APK
      run: |
        zipalign -v 4 bin_android/*.apk bin_android/GalaxyBudsClient_arm64.apk

    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: GalaxyBudsClient_Android_arm64
        path: bin_android/GalaxyBudsClient_arm64.apk

  attach-to-release:
    runs-on: ubuntu-latest
    needs: [build-arm64]
    if: github.event_name == 'release'

    steps:
    - name: Download APK artifact
      uses: actions/download-artifact@v4
      with:
        name: GalaxyBudsClient_Android_arm64

    - name: Attach APK to release
      uses: AButler/upload-release-assets@v2.0
      with:
        files: bin_android/GalaxyBudsClient_arm64.apk
        repo-token: ${{ secrets.GH_TOKEN }}
